# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-14 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tag',
            new_name='user_or_group',
        ),
        migrations.AlterField(
            model_name='task',
            name='username',
            field=models.CharField(max_length=20, verbose_name='username'),
        ),
    ]
