# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='authority',
            field=models.CharField(default='common_user', max_length=20, verbose_name='priority'),
        ),
    ]
