# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-15 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_users_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('project_name', models.CharField(max_length=100, verbose_name='project_name')),
                ('authority', models.IntegerField(default=5, verbose_name='priority')),
                ('request_serial_num', models.IntegerField(verbose_name='request_order')),
                ('task_priority', models.IntegerField(verbose_name='task_priority')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='email'),
        ),
    ]
