# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190314_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ptn_name',
            field=models.CharField(default='mul5', max_length=30, verbose_name='ptn_file_name'),
        ),
    ]
