# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alltask4user'),
    ]

    operations = [
        migrations.CreateModel(
            name='allTask4group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter', models.CharField(max_length=20, verbose_name='username')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='submit_time')),
                ('finish_time', models.DateTimeField(auto_now=True, verbose_name='finish_time')),
                ('finish_tag', models.BooleanField(default=False, verbose_name='tag')),
                ('project_loc', models.CharField(max_length=100, verbose_name='project_loc')),
                ('ptn_name', models.CharField(max_length=30, verbose_name='ptn_file_name')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Group')),
            ],
        ),
    ]
