# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20190116_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='request_serial_num',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='request_serial_num'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='username'),
        ),
    ]
