# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20190116_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='authority',
            field=models.CharField(max_length=20, verbose_name='authority'),
        ),
    ]
