# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-29 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20190329_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_db',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='task_db',
            name='task_priority',
        ),
    ]
